baseurl = "www.robinkrijgsman.com"
title = "Robin Krijgsman"
author = "Robin Krijgsman"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = ""
description = "portfolio website for robin krijgsman"
bgimg = "img/stripes.jpg"
